[package]
name = "account"
version = "0.1.0"
edition = "2021"
authors = ["dravenk <longxianwen@outlook.com>"]
description = "account."
readme = "README.md"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/account"

[dependencies]
